name: Python application

on:
  issues:
    types: [opened]
  schedule:
    - cron: 40 12 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Latest Data
      run: |
        python get_new_data.py
        python produce_html.py
    - name: Push Plus
      run: |
        python push.py
      env:
        token: ${{ secrets.token }}
    - name: Commit files
      run: |
        git config --local user.email "johnhaung@163.com"
        git config --local user.name "huanghaozi"
        git commit -m "Update Data by bot, scripted by HH" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
